### ISSUE TITLE
Few questions

### ISSUE THREAD

**Issue by shoaibrashid** [SensorsIot/IFTTT-Dash-Button#1]
I have few question about this sketch. 
1-Why you called yield inside main loop?
2-Why you never call method named "ShutDown"
I have deployed this code to ESP01. Problem is it is getting overheating. 
For Power up i am using Soshine Single Cell (700mah) without any Voltage Regulator. Your video for this is quite confusing regarding what you have on you Custom PCB. Even you never listed full components.  Diagram available is not understable by beginners.

**Comment by shoaibrashid** [comment]
It would be great if you can list minimum components required.

**Comment by shoaibrashid** [comment]
It would be great if you can list minimum components required.

**Comment by battika** [comment]
I guess the answer to your questions:
1. yield() means no operation but gives a chance for the watchdog process not to shut down the system thinking it is stuck. This sketch is not using the main loop anyway. 
More info [here](https://learn.sparkfun.com/tutorials/esp8266-thing-hookup-guide/using-the-arduino-addon)
2. Probably Andreas changed his mind and he calls deep sleep directly on line 71. You can replace that line with calling the shutdown function if you wish.

**Comment by battika** [comment]
List of components should be straight forward by looking at the schematics:
- ESP-01 or ESP-01S
- 2 x 10k resistor
- 220 Ohm resistor
- switch for reset button
- LED switch for action button - or just a normal button and a separate LED
- 1000 uF capacitor
