### ISSUE TITLE
Void shutdown() not referenced

### ISSUE THREAD

**Issue by bwims** [SensorsIot/IFTTT-Dash-Button#3]
You appear to have copied over the shutdown procedure from https://github.com/pinae/ESP8266-Dash, but you do not reference it like she does. 

I guess it is not necessary and can be deleted?

**Comment by SensorsIot** [comment]
As written in the header it is inspired by this repo. It is part of an overall project.

**Comment by bwims** [comment]
I don't think you understood me.  You modified the shutdown to tidy up, which was good, but you never call it.   The last line after serial.println("Going to sleep."); should not be ESP.deepSleep(0); , but shutdown();  That way the LED will get set low before going to sleep.

It's really up to you, but modifying a routine and not calling it looks like a bug to me!
